version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/www:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: graphrag
      MYSQL_PASSWORD: nvidia
      MYSQL_DATABASE: agentic_app

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agentic_app
      MYSQL_USER: graphrag
      MYSQL_PASSWORD: nvidia
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf   